telegram_bot:
  token: ""

openai:
  api_key: ""

deepseek:
  api_key: ""

google:
  client_id: ""
  client_secret: ""
  redirect_url: "http://localhost:8080/oauth2callback/google"

rest:
  port: 8080
  https: false
  domain: "localhost"

database:
  url: "${DATABASE_URL}"