services:
  bot:
    image: ghcr.io/ivgag/schedulr:latest
    network_mode: "host"
    ports:
      - "443:443"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      CONFIG_NAME: ".config-prod.yml"
      CONFIG_PATH: "/etc/schedulr"