services:
  bot:
    container_name: schedulr-bot
    image: ghcr.io/ivgag/schedulr:latest
    network_mode: "host"
    ports:
      - "443:443"
      - "80:80"
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      CONFIG_NAME: ".config-prod.yml"
      CONFIG_PATH: "/etc/schedulr"
    volumes:
      - /etc/scheduler/.config-prod.yml:/etc/schedulr/.config-prod.yml
      - /etc/scheduler/certs:/certs
    restart: always