services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: schedulr
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d schedulr"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      CONFIG_NAME: ".config-dev"
      CONFIG_PATH: "/etc/schedulr"
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/schedulr?sslmode=disable"
    volumes:
      - .:/etc/schedulr
    depends_on:
      postgres:
        condition: service_healthy
        restart: true